### ISSUE TITLE
The switch case in the code

### ISSUE THREAD

**Issue by JohanJermey** [pytimer/k8sutil#2]
HI,

Thanks we start using this lib and it works great.

is this https://github.com/pytimer/k8sutil/blob/main/apply/apply.go#L241 code is needed, as it seems that this is a bug ???
Please correct me if I wrong as the it returns the same error always if you create new object...
https://github.com/kubernetes/apimachinery/blob/e6c90c4366be1504309a6aafe0d816856450f36a/pkg/runtime/scheme.go#L296-L302

Thanks

**Comment by pytimer** [comment]
Sorry to reply late.

> Please correct me if I wrong as the it returns the same error always if you create new object...

Did you use apply like https://github.com/pytimer/k8sutil/blob/main/examples/apply/main.go#L76, but something went wrong? I don't understand it clearly, can you explain it, thanks. 

If you have example, it must be great.

**Comment by JohanJermey** [comment]
HI, 

No it works great, thanks.
I try to learn this code as we want to use it in production. everything is clear except for this switch statement.
For this...

`versionedObject, err := runtime.NewScheme().New(gvk)`

Do you think that this switch can happen, https://github.com/pytimer/k8sutil/blob/main/apply/apply.go#L241
I think that the first switch (`case runtime.IsNotRegisteredError(err):`)  will always be valid or maybe the error. (last)

is there a case that the `case err == nil`  will be valid?

Thanks

**Comment by JohanJermey** [comment]
HI, 

No it works great, thanks.
I try to learn this code as we want to use it in production. everything is clear except for this switch statement.
For this...

`versionedObject, err := runtime.NewScheme().New(gvk)`

Do you think that this switch can happen, https://github.com/pytimer/k8sutil/blob/main/apply/apply.go#L241
I think that the first switch (`case runtime.IsNotRegisteredError(err):`)  will always be valid or maybe the error. (last)

is there a case that the `case err == nil`  will be valid?

Thanks

**Comment by pytimer** [comment]
> Do you think that this switch can happen, https://github.com/pytimer/k8sutil/blob/main/apply/apply.go#L241
I think that the first switch (case runtime.IsNotRegisteredError(err):) will always be valid or maybe the error. (last)

This `case runtime.IsNotRegisteredError(err)` case mean that if the `runtime.Object` no go struct to registerd the target gvk,  it will return [notRegisteredErr](https://github.com/kubernetes/apimachinery/blob/153f11a7f300ab3b1fd3f5d0b5cf6763b79a61dd/pkg/runtime/error.go#L27), so this case is to support unstructured objects.

> is there a case that the case err == nil will be valid?

If the object is k8s build-in resources, it maybe return err == nil.

You can reference this PR: [apply falls back to generic JSON patch computation if no go struct is registered for the target GVK](https://github.com/kubernetes/kubernetes/pull/40666), maybe it help you.

If you have any other doubts, welcome to point it.

**Comment by JohanJermey** [comment]
Thanks a lot!
You write: "If the object is k8s build-in resources, it maybe return err == nil." , can you think of scenario where I can reproduce this case ?

**Comment by JohanJermey** [comment]
in addition, just if you have time :) , i was able to do some unit test for some of the functions, but im struggling with this function 

https://github.com/pytimer/k8sutil/blob/main/apply/apply.go#L119 

I start it with 

```
	dynamicfake "k8s.io/client-go/dynamic/fake"
	k8sfake "k8s.io/client-go/kubernetes/fake"
	k8stesting "k8s.io/client-go/testing"

```
```

		applyOptions = ApplyOptions{
			discoveryClient: k8sfake.NewSimpleClientset().Discovery(),
			dynamicClient:   dynamicfake.NewSimpleDynamicClient(runtime.NewScheme()),
		}
```


and I got error here: https://github.com/pytimer/k8sutil/blob/main/apply/apply.go#L139 as it doesnt have the deployment.

pkg/api/meta/multirestmapper.go 


in the function `RESTMappings` as it have empty `MultiRESTMapper` , any idea how to initiate it? 
I tried with that but it seems that it isnt sufficient...
`discoveryClient: k8sfake.NewSimpleClientset().Discovery(),`

**Comment by pytimer** [comment]
> Thanks a lot! You write: "If the object is k8s build-in resources, it maybe return err == nil." , can you think of scenario where I can reproduce this case ?

Sorry, i didn't make it clear. You should register k8s build-in resources schema first, then apply, it will return err == nil. Like below code:

```go
import (
      appsv1 "k8s.io/api/apps/v1"
      utilruntime "k8s.io/apimachinery/pkg/util/runtime"
      "k8s.io/apimachinery/pkg/runtime"
)

var Scheme = runtime.NewScheme()

func init() {
	utilruntime.Must(appsv1.AddToScheme(Scheme))
}
```

This apply package now not register any resources schema, so it always return `notRegisteredErr`. I will consider add this feature to this package.

**Comment by pytimer** [comment]
> in the function RESTMappings as it have empty MultiRESTMapper , any idea how to initiate it?

I testing RESTMapping in my other repo, hope it can help you.

***source code:***

```go
func NewDynamicResourceClient(c Client, namespace, resourceGroupName string, version string) (*DynamicResourceClient, error) {
	mapper, err := c.ToRESTMapper()
	if err != nil {
		return nil, errors.Wrapf(err, "unable to get RESTMapper")
	}

	gvr := schema.GroupVersionResource{Resource: resourceGroupName}
	if version != "" {
		gvr.Version = version
	}

	singleGroupVersionResource, err := mapper.ResourceFor(gvr)
	if err != nil {
		return nil, errors.Wrap(err, "unable to get resource group version")
	}
	klog.V(4).Infof("resource group version: %+v", gvr)

	gvk, err := mapper.KindFor(gvr)
	if err != nil {
		return nil, errors.Wrap(err, "unable to get resource kind")
	}
	klog.V(4).Infof("resource version kind: %+v", gvk)

	restMapping, err := mapper.RESTMapping(gvk.GroupKind(), gvk.Version)
	if err != nil {
		return nil, err
	}
	klog.V(4).Infof("rest mapping: %v", restMapping.Scope.Name())

	dc := &DynamicResourceClient{}
	if restMapping.Scope.Name() == meta.RESTScopeNameNamespace {
		if namespace == "" {
			namespace = metav1.NamespaceAll
		}
		dc.client = c.Dynamic().Resource(singleGroupVersionResource).Namespace(namespace)
	} else {
		dc.client = c.Dynamic().Resource(singleGroupVersionResource)
	}

	return dc, nil
}
```

***testing***

```go
func TestNewDynamicResourceClient(t *testing.T) {
	dynamicClient := dynamicfake.NewSimpleDynamicClient(runtime.NewScheme())
	type Test struct {
		name          string
		resourceName  string
		namespace     string
		version       string
		discovery     discovery.DiscoveryInterface
		expected      *DynamicResourceClient
		expectedError error
	}
	for _, test := range []Test{
		{
			name:         "normal",
			resourceName: "foo",
			discovery: &discoveryfake.FakeDiscovery{
				Fake: &k8stesting.Fake{
					Resources: []*metav1.APIResourceList{
						&aResources,
						&bResources,
					},
				},
			},
			expected: &DynamicResourceClient{
				client: dynamicClient.Resource(aGroup),
			},
			expectedError: nil,
		},
		{
			name:         "specified version",
			resourceName: "foo",
			version:      "v1",
			discovery: &discoveryfake.FakeDiscovery{
				Fake: &k8stesting.Fake{
					Resources: []*metav1.APIResourceList{
						&aResources,
						&bResources,
					},
				},
			},
			expected: &DynamicResourceClient{
				client: dynamicClient.Resource(aGroup),
			},
			expectedError: nil,
		},
		{
			name:         "b namespace",
			resourceName: "bar",
			version:      "v1",
			namespace:    "default",
			discovery: &discoveryfake.FakeDiscovery{
				Fake: &k8stesting.Fake{
					Resources: []*metav1.APIResourceList{
						&aResources,
						&bResources,
					},
				},
			},
			expected: &DynamicResourceClient{
				client: dynamicClient.Resource(bGroup).Namespace("default"),
			},
			expectedError: nil,
		},
		{
			name:         "b default namespace",
			resourceName: "bar",
			version:      "v1",
			namespace:    metav1.NamespaceAll,
			discovery: &discoveryfake.FakeDiscovery{
				Fake: &k8stesting.Fake{
					Resources: []*metav1.APIResourceList{
						&aResources,
						&bResources,
					},
				},
			},
			expected: &DynamicResourceClient{
				client: dynamicClient.Resource(bGroup).Namespace(""),
			},
			expectedError: nil,
		},
		{
			name:         "c group version format wrong",
			resourceName: "foos",
			discovery: &discoveryfake.FakeDiscovery{
				Fake: &k8stesting.Fake{
					Resources: []*metav1.APIResourceList{
						&cResources,
					},
				},
			},
			expected:      nil,
			expectedError: fmt.Errorf("a failed"),
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			// k8s fake client
			client := NewFakeClient(nil, nil, dynamicClient, test.discovery, nil)
			got, err := NewDynamicResourceClient(client, test.namespace, test.resourceName, test.version)
			if err == nil && test.expectedError != nil {
				t.Fatalf("expected error %q, but got none", test.expectedError)
			} else if err != nil && test.expectedError == nil {
				t.Fatalf("expected error none, but got %q", err)
			}

			if !reflect.DeepEqual(test.expected, got) {
				t.Errorf("unexpected result:\nexpected=%#v\ngot=%#v", test.expected, got)
			}
		})
	}
}

var (
	aResources = metav1.APIResourceList{
		GroupVersion: "a/v1",
		APIResources: []metav1.APIResource{aFoo},
	}
	aFoo = metav1.APIResource{
		Name:       "foo",
		Kind:       "Foo",
		Namespaced: false,
	}
	aGroup = schema.GroupVersionResource{
		Group:    "a",
		Version:  "v1",
		Resource: "foo",
	}
	bResources = metav1.APIResourceList{
		GroupVersion: "b/v1",
		APIResources: []metav1.APIResource{bBar},
	}
	bBar = metav1.APIResource{
		Name:       "bar",
		Kind:       "Bar",
		Namespaced: true,
	}
	bGroup = schema.GroupVersionResource{
		Group:    "b",
		Version:  "v1",
		Resource: "bar",
	}
	cResources = metav1.APIResourceList{
		GroupVersion: "c/v1/cc",
		APIResources: []metav1.APIResource{},
	}
)
```

**Comment by pytimer** [comment]
Update code that register default resource schema use [client-go support schema](https://github.com/kubernetes/client-go/blob/v0.20.2/kubernetes/scheme/register.go#L75) now.

If you want to register other resource schema, like crd, etc. You can look [the new apply example](https://github.com/pytimer/k8sutil/blob/c63171c7e6e0b3a38df51b4da7e1bc9309b2c728/examples/apply/main.go#L78).

**Comment by JohanJermey** [comment]
Thanks! you helped me a lot! 
One last questions: (regard the supported schema), does it mean that the code before the change dosent support CRD, So In case I've created new CRD and I wanted to  use the code so I need to add it like `imagepolicyv1alpha1.AddToScheme(apply.Scheme))`   ? or this is different issue ?


in addition can you please provide the code for the test, some link if possible currenlty i miss those implementation .

```
client := NewFakeClient(nil, nil, dynamicClient, test.discovery, nil)
got, err := NewDynamicResourceClient(client, test.namespace, test.resourceName, test.version)
```

**Comment by pytimer** [comment]
> does it mean that the code before the change dosent support CRD, So In case I've created new CRD and I wanted to use the code so I need to add it like imagepolicyv1alpha1.AddToScheme(apply.Scheme)) ? or this is different issue ?

The package always support CRD, but apply always exec [case runtime.IsNotRegisteredError(err)](https://github.com/pytimer/k8sutil/blob/main/apply/apply.go#L227) case before change scheme.
If you add `AddToScheme(apply.Scheme)`  before apply, the apply workflow will exec `err == nil` case.

If you want write testing code, you should use discovery fake client to register some resources, like below code.

```go
discovery: &discoveryfake.FakeDiscovery{
  Fake: &k8stesting.Fake{
	  Resources: []*metav1.APIResourceList{
		  &aResources,
		  &bResources,
	  },
  },
},
```

```go
func NewFakeClient(config *rest.Config, k8sClient kubernetes.Interface,
	dynamicClient dynamic.Interface, discoveryClient discovery.DiscoveryInterface, metricClient resourceclient.Interface) Client {
	if config != nil {
		rest.AddUserAgent(config, constant.KubernetesResourceManager)
	}

	k := &kubernetesClient{
		k8s:            k8sClient,
		dynamic:        dynamicClient,
		discovery:      discoveryClient,
		resourceMetric: metricClient,
	}
	k.config = config

	return k
}

func (k *kubernetesClient) ToRESTMapper() (meta.RESTMapper, error) {
        // This use discoveryClient
	gr, err := restmapper.GetAPIGroupResources(k.Discovery())
	if err != nil {
		return nil, err
	}

	mapper := restmapper.NewDiscoveryRESTMapper(gr)
	return mapper, nil
}
```

**Comment by JohanJermey** [comment]
Thanks a lot! I understand now the logic great!

I've question regard the util.


https://github.com/pytimer/k8sutil/blob/8ec04321364a259537e9144b4d9fc7d40ccfaa7b/util/apply.go#L35

what do you mean if object was read from command input ?
server side ? 

command input is the cli? 
server is the resources inside k8s ? 

and why you are deleting it and adding it again ?


Thanks for your help!

**Comment by pytimer** [comment]
The apply package implement like `kubectl`, it will write latest object to resource annotation if not use server-side apply. When the next apply, it will compare the annotation latest object and current object.

**Comment by pytimer** [comment]
close. If have other problem, reopen it.
